#!/usr/bin/env node
// Copies the kaspa-keygen SDK (glue + wasm) from the sibling rusty-kaspa
// checkout into src/kaspa/, embedding the wasm as base64 so it loads
// identically in debug and release bundles. Run before bundling:
//   node scripts/sync-kaspa.js
const fs = require('fs');
const path = require('path');

const TIERS = [
  {tier: 'kaspa-keygen', dir: 'kaspa'},
  {tier: 'kaspa-rpc', dir: 'kaspa-rpc'},
];

for (const {tier, dir} of TIERS) {
  const source = path.resolve(__dirname, '../../../rusty-kaspa/wasm/web/' + tier);
  const target = path.resolve(__dirname, '../src/' + dir);
  syncTier(source, target, tier);
}

function syncTier(source, target, tier) {
if (!fs.existsSync(path.join(source, 'kaspa_bg.wasm'))) {
  console.error(`kaspa-keygen build not found at ${source}`);
  console.error('build it with: cd rusty-kaspa/wasm && ./build-web --keygen');
  process.exit(1);
}

fs.mkdirSync(target, {recursive: true});

for (const file of ['kaspa.js', 'kaspa.d.ts']) {
  let content = fs.readFileSync(path.join(source, file), 'utf8');

  // Hermes' bytecode compiler rejects `import.meta`. It only appears in the
  // glue's URL fallback (used when init() is called without bytes), a path
  // this app never takes — bytes are always provided.
  if (file.endsWith('.js')) {
    content = content.replace(
      /import\.meta\.url/g,
      'undefined /* import.meta.url unsupported by Hermes; bytes are always provided */'
    );

    // Defence in depth: refresh cached typed-array views when the memory
    // object identity changes (this binding rebuilds `memory.buffer` on
    // grow). Memory is non-moving in the wasm3 backend, so stale views are
    // no longer corrupting — this keeps view lengths current regardless.
    content = content.replace(
      /(cached(\w+)ArrayMemory(\w*) === null \|\| cached\w+ArrayMemory\w*\.byteLength === 0)/g,
      (m, g1, type, idx) =>
        `${g1} || cached${type}ArrayMemory${idx}.buffer !== wasm.memory.buffer`
    );
  }

  fs.writeFileSync(path.join(target, file), content);
}

const wasm = fs.readFileSync(path.join(source, 'kaspa_bg.wasm'));

fs.writeFileSync(
  path.join(target, 'kaspa-wasm.js'),
  '// Generated by scripts/sync-kaspa.js — do not edit.\n' +
    "const base64 = '" +
    wasm.toString('base64') +
    "';\n" +
    'const table = new Uint8Array(128);\n' +
    "const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';\n" +
    'for (let i = 0; i < chars.length; i++) table[chars.charCodeAt(i)] = i;\n' +
    'export function kaspaWasmBytes() {\n' +
    "  const clean = base64.replace(/=+$/, '');\n" +
    '  const out = new Uint8Array((clean.length * 3) >> 2);\n' +
    '  let o = 0;\n' +
    '  for (let i = 0; i + 3 < clean.length + 1; i += 4) {\n' +
    '    const a = table[clean.charCodeAt(i)];\n' +
    '    const b = table[clean.charCodeAt(i + 1)];\n' +
    '    const c = i + 2 < clean.length ? table[clean.charCodeAt(i + 2)] : 0;\n' +
    '    const d = i + 3 < clean.length ? table[clean.charCodeAt(i + 3)] : 0;\n' +
    '    out[o++] = (a << 2) | (b >> 4);\n' +
    '    if (i + 2 < clean.length) out[o++] = ((b & 15) << 4) | (c >> 2);\n' +
    '    if (i + 3 < clean.length) out[o++] = ((c & 3) << 6) | d;\n' +
    '  }\n' +
    '  return out;\n' +
    '}\n'
);

console.log(
  `synced ${tier} (${(wasm.length / 1048576).toFixed(1)}MB wasm) to ${target}`
);
}
